### PR TITLE
Menu for hiding old videos and mix-es

### PR DESCRIPTION
**Pull request by actionless**
2020-03-16--1584369607_297x224_scrot

### CODE REVIEW

**Comment by actionless** [comment]
because sometimes/often i just don't wanna watch some old videos, but all the latest, but youtube itself is not giving such option, except for trending videos, which is not exactly what i need as they usually not correlate to my watching history

**Comment by netjeff** [comment]
> because sometimes/often i just don't wanna watch some old videos, 

@actionless, Seems like you could just stop scrolling when the videos get older than you want to watch?

**Comment by actionless** [comment]
No, for frontpage that wouldnt work. And for search results changing
sorting to "by date" will bring up some less relevant videos.

**Comment by EvHaus** [comment]
I think the feature is really cool, but it's not really a direction that I want for this project. The goal of `youtube-hide-watched` is to stay simple and focus only on controlling filtering of videos based on your watched status. I worry that by merging this feature in, it's going to add additional scope to the project that I'm not really interested in having to maintain.

However, my code is 100% open source, so I would encourage you to fork it and release this branch as a new userscript. I'm sure others would be interested in what you've created and it would make for a cool project of its own. I think both of these features can exist together as 2 projects.

Good luck!

**Pull request closed without merging**
