### PR TITLE
Use button instead of GM_registerMenuCommand

### PR DESCRIPTION
**Pull request by jas32096**
UserScripts doesn't support `GM_registerMenuCommand` see https://github.com/quoid/userscripts/issues/230.

This MR updates the code to remove it and, instead, use a new button, added to the page.

Screenshot 2023-06-18 at 10 19 02 AM

### CODE REVIEW

**Comment by EvHaus** [comment]
Thanks for the PR! It's a shame Safari doesn't have native support for `GM_registerMenuCommand`. 😢 

I'm a bit hesitant with adding another UI element to the menu though. I feel like 3 icons from one userscript is quite a lot. Especially since they all look like native YouTube UI elements which users might confuse for some official settings feature.

I wonder if maybe it's time to implement a single button with a chevron, that would open a custom dropdown instead. Something like this:

image

**Comment by jas32096** [comment]
Agreed, it could be confusing, looking at it, without context. However, I expect a user, having installed the script, would have a baseline understanding of what it does. At least, if we document it.

I like your idea of a dropdown menu, but I'm not a Javascript developer, so I suspect that would have to be implemented by someone else. Though, I would recommend retaining the dedicated "shorts" button, for easy access.

We could consider using the context menu, but I could not find a way to, sensibly, do that, without creating an additional userscript.

**Comment by mc-hamster** [comment]
Confirmed that this fixes the bug in Safari on Mac.

**Comment by EvHaus** [comment]
Thank you for the work on this @jas32096. I've merged it (with some additional UI improvements) and will release as v6.

**Comment by jas32096** [comment]
Glad this got merged. Thanks for the cleanup, too. I'm also having the same issue as #191, while in Light Mode. Works fine in Dark Mode, however.

**Pull request merged**
