### PR TITLE
Fixed not dimming/hiding watched items on channel page

### LINKED ISSUE #113: Does not work since recent YouTube style change
YouTube changed it's style a few days ago. Since then, the script does not work anymore.

The button to show/dim/hide watched videos appears but clicking on it does not change anything in the video list.

My browser console also does not show anything related to that.

Browser: Mozilla Firefox v106.0.2
Script version: v4.4.1
Userscript Manager: Tampermonkey v4.18.0

### PR DESCRIPTION
**Pull request by Programie**
This fixes #113.

### CODE REVIEW

**Comment by netjeff** [comment]
FYI, YT Premium accounts not experiencing the updated CSS (yet?).  See discussion on #113

**Comment by Programie** [comment]
Maybe supporting both variants might be the best option for now?

I.e. adding `item.closest('.ytd-grid-renderer')` to
```
watchedItem = (
    item.closest('ytd-rich-item-renderer') ||
    item.closest('ytd-video-renderer') ||
    item.closest('ytd-grid-video-renderer')
);
```

**Comment by Programie** [comment]
I just saw that adding `item.closest('.ytd-grid-renderer')` is not required as it is already found by `item.closest('ytd-grid-video-renderer')`

**Comment by EvHaus** [comment]
Works well in my testing. Thanks for the contribution!

**Comment by netjeff** [comment]
YT Premium still working for me, too.  Thanks @Programie!

**Pull request merged**
